### ISSUE TITLE
Security issue with link in FunctionalNotes.md

### ISSUE THREAD

**Issue by RdrSeraphim** [Wilbeibi/NotesIndex#1]
The link "http://blog.sigfpe.com/2006/08/you-could-have-invented-monads-and.html" has a website "http://tex.yourequations.net" set as a script file. That script file tries to install the Sweet Orange root kit each time it connects.

**Comment by wilbeibi** [comment]
Thank you. My friend and I have not meet such problem. And this link is also recommended by ycombinator and haskell.org. Well, I will put a warning besides the link, thank you.
